name: Deploy to dev server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-req=ext-imagick

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Create Database
      run: |
        mysql -e 'CREATE DATABASE IF NOT EXISTS doctorly.db;'
    - name: Migrate
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: doctorly_db
        DB_USERNAME: admin
        DB_PASSWORD: password
      run: php artisan migrate

    - name: Passport Install
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: doctorly_db
        DB_USERNAME: admin
        DB_PASSWORD: password
      run: php artisan passport:install

    - name: Clear Cache
      run: php artisan optimize:clear

    - name: Run tests
      env:
        DB_CONNECTION: sqlite
        DB_CONNECTION_LOG: sqlite
        DB_DATABASE: database/database.sqlite
        DB_LOG_DATABASE: database/database.sqlite
      run: php artisan test

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-req=ext-imagick
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache deploy

    - name: Pre Deploy
      uses: appleboy/ssh-action@master
      with:
          username: ${{ secrets.DEV_REMOTE_USER }}
          host: ${{ secrets.DEV_REMOTE_HOST }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
              cd ${{ secrets.DEV_REMOTE_TARGET }} && php artisan down

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.DEV_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.DEV_REMOTE_USER }}
          TARGET: ${{ secrets.DEV_REMOTE_TARGET }}
          EXCLUDE: "/storage/, /bootstrap/, .env"

    - name: Post Deploy
      uses: appleboy/ssh-action@master
      with:
          username: ${{ secrets.DEV_REMOTE_USER }}
          host: ${{ secrets.DEV_REMOTE_HOST }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
              cd ${{ secrets.DEV_REMOTE_TARGET }} && php artisan up
